---
title: "FAQs"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{FAQs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

### 1. Why does an optimised scenario with a budget equal to (or less), than the Global Plan have greater impact?

The Global Plan specified broad intervention scale-up projections that were, in
most instances (not all) at the country level. As such, there is space for an
increase in efficiency, resulting in a greater impact for the same or less
spending, with optimal sub-national targeting of interventions. This is what the
optimised solutions are in the Global Fund runs.

### 2. Why does a decrease in the budget of optimised solutions occasionally result in increased impact?

There are a number of reasons why this could occur, Firstly the optimisation is
set up to minimise and equally weighted sum of cases and deaths. Therefore an
increase in one output, may be outweighed by a decrease in the other. In this 
case the aggregate weighted sum of cases and deaths will have increased with 
a smaller budget.

Secondly, One of the conditions of the budget optimisation is that treatment 
must be the last intervention for which coverage is reduced when reducing the 
available budget. This is implemented by removing any lower-coverage treatment 
options when the budget is high enough. When the budget is reduced below this 
threshold the lower-coverage treatment options become available again. For low 
incidence settings, due to model stochastic, it is possible for a run with 
lower tx coverage to have lower case numbers than a run with higher treatment 
coverage.

### 3. Why does the weighted sum of cases and deaths (y) decrease with b for the scenario `post = continue`, whilst not always for the scenario `post = gp`?

This seems counter intuitive as we wouldn't expect the post-replenishement period to 
have any impact on the replenishment period! The optimisation is run on the `post = continue`
scenario. When we apply this optimal solution to the `post = gp` scenario it is applied to 
a different set of model runs. These vary stochastically from the `post = continue` runs. This
stochastic variation can lead to the weighted sum of cases and deaths (y) not always decreasing
monotonically with b. This problem will be most pronounced in low transmission countries where
the stochastic variation is more influential.

### 4. Why is the budget for a given `b` scenario not always `<=  b * global plan budget`?

For the same reason as above, stochastic differences in the treatment costs for the `post = gp`
can lead to small fluctuations in the total cost. 

### 5. How do I filter outputs to select a specific scenario?

Filtering a specific scenario can be performed by selecting the relevant 
scenario options from the pre, replenishment and post scenario columns. For 
budget optimisation outputs, select the relevant pre and post scenarios and the
required budget proportion (e.g. `pre = Follow_GP`, `replenishement = 0.75` and
`post = Revert_to_GP`). For fixed scenarions, select the relevant pre,
replenishment and post scenarios (e.g. `pre = Follow_GP`, `replenishment = Revert_to_GP`
and `post = Revert_to_GP`). Please see the 
[companion output dictionary vignette](Output_dictionary.html) for more help.

### 6. Can I interpolate intervention coverage between optimised budget levels?

In most cases yes, however intervention trends over multiple budget steps may
not be linear or monotonic. As a result it is suggested to always interpolate
between single budget steps (e.g. 0.6 to 0.65), not across multiple 
(e.g. 0.6 to 0.8). Optimised output is provided with steps of 0.05 to 
facilitate this.

### 7. Why do some countries not have the full compliment of budget levels?

In a number of cases the solutions of lower budget levels are not possible as
the minimum cost solution for the country exceeds these lower budget bounds. As
no solution can be found in these instances, the output is omitted. 

### 8. Why does impact not decrease linearly as b decreases?

As the budget decreases we must remove interventions to decrease costs accordingly.
Treatment is prioritised in the optimisation and not reduced before all other interventions have been removed. This
means we must remove preventative interventions, such as LLINs first. Reducing these
interventions can lead to increased transmission and, for a fixed treatment coverage,
an increase in treatment costs. This creates a threshold condition whereby either very
large decreases in coverage must be made in a single step (to offset both the decrease in 
budget and associated rise in treatment cost), or none at all. The point at which
this big jump from high to low (or no) coverage occurs corresponds to a big jump in 
cases and deaths. The level of b where this happens is transmission dependent.
